### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DentyTxR** [SomewhatSane/VPNShield-EXILED-Edition#2]
Would be cool if on certain events (such as an IP getting blocked or someone trying to connect with a blocked IP) send a discord webhook to a channel

**Comment by SomewhatSane** [comment]
I'm sorry for how long it's taken me to notice this. I'll put your suggestion into consideration! 😄

**Comment by SomewhatSane** [comment]
Primitively addressed in v3.0.0.0. I'll expand on this feature in the future!
